# server
server.port=443
server.ssl.enabled=true
server.ssl.key-store=keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=1234
server.ssl.key-password=1234

# file
file.upload.path=/src/main/resources/static/
file.down.path=http://localhost/static/


